### ISSUE TITLE
Aborts with killed

### ISSUE THREAD

**Issue by BennyWindolph** [superiss/spidy#4]
Spidy aborts with "Killed". Do you have a clue why?

Thanks!

**Comment by twiny** [comment]
Hey @BennyBolivar

Could you please share more details the logs, error messages ?

I will check it out!

Thank you for submitting the issue.

**Comment by BennyWindolph** [comment]
After a while the sessions ends with "Killed".I run it on a digital ocean droplet with ubuntu 22.04 and i tried to crawl entire wordpress.orgThank you!Am 26.08.2022 17:20 schrieb Iss M ***@***.***>:
Hey @BennyBolivar
Could you please share more details the logs, error messages ?
I will check it out!
Thank you for submitting the issue.

**Comment by twiny** [comment]
@BennyBolivar - I think the droplet ran out of memory. could try it again and monitor droplet - memory/cpu usage!

I will test with wordpress.org and see

**Comment by BennyWindolph** [comment]
Ah, simple solution then. Will upgrade and try again. Thank you!Am 26.08.2022 19:18 schrieb Iss M ***@***.***>:
@BennyBolivar - I think the droplet ran out of memory

**Comment by twiny** [comment]
yes - but there could be a memory leak somewhere. try monitoring memory/cpu on droplet. enable log..etc

I will try this out as well

**Comment by BennyWindolph** [comment]
Will do!If you want to reproduce the error, i used the cheapest basic droplet with just 1 Gig of Ram.Am 26.08.2022 19:26 schrieb Iss M ***@***.***>:
yes - but there could be a memory leak somewhere. try monitoring memory/cpu on droplet. enable log..etc
I will try this out as well
